{% set name = "esi-core" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/esi-core/-/archive/{{ version }}/esi-core-{{ version }}.tar.gz
  sha256: c1c828af4fc9a169a75fb178a692e4c253c05d065f8a768f0b2b307b2d3e8766

build:
  skip: true  # [py>=311]
  skip: true  # [py<38]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.23,<3                    # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23,<3
    - numpy
    - setuptools-scm >=3.4
    - pip
  run:
    - python
    - obspy >=1.3.0

test:
  imports:
    - esi_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://code.usgs.gov/ghsc/esi/esi-core
  summary: Repository for compiled code used by ESI projects.
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - emthompson-usgs
