{% set name = "esi-core" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/esi-core/-/archive/{{ version }}/esi-core-{{ version }}.tar.gz
  sha256: c1c828af4fc9a169a75fb178a692e4c253c05d065f8a768f0b2b307b2d3e8766

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools-scm
    - pip
  run:
    - python
    - obspy >=1.3.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - esi_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://code.usgs.gov/ghsc/esi/esi-core
  summary: Repository for compiled code used by ESI projects.
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - emthompson-usgs
