schema_version: 1

context:
  version: "1.2.5"

package:
  name: esi-core
  version: ${{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/esi-core/-/archive/v${{ version }}/esi-core-v${{ version }}.tar.gz
  sha256: 25ead647542d4e2577060f4b892c083bd429ca9bda8c3dff76b68522a755c3c7

build:
  script:
    - if: not win
      then:
        - export SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - if: win
      then:
        - set SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv
  number: 0
  skip: match(python, ">=3.14")

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools >=42
    - setuptools-scm >=3.4
    - cython >=3.0.0
    - numpy >=1.26
    - pip
  run:
    - python
    - obspy >=1.3.1
    - six >=1.16
    - numpy

tests:
  - python:
      imports:
        - esi_core
      pip_check: true

about:
  homepage: https://code.usgs.gov/ghsc/esi/esi-core
  summary: Repository for compiled code used by ESI projects.
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - emthompson-usgs
